# aaa
# NameError
# d = {'x':1,'y':2}
# d['z']
# KeyError
# L = [1,2]
# L[2]
# # IndexError

# try:
#     # d = {'x':1,'y':2}
#     # d['z']
#     aaa
# except Exception as f:
#     print('捕获到异常',f)